"""create CRUD class table

Revision ID: 43256e4657c2
Revises: e48961c75a70
Create Date: 2025-05-13 17:11:45.111691

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '43256e4657c2'
down_revision = 'e48961c75a70'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('class_lecturers', schema=None) as batch_op:
        batch_op.alter_column('semester',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('academic_year',
               existing_type=sa.VARCHAR(length=9),
               nullable=True)

    with op.batch_alter_table('classes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('semester', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('academic_year', sa.String(length=9), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('classes', schema=None) as batch_op:
        batch_op.drop_column('academic_year')
        batch_op.drop_column('semester')

    with op.batch_alter_table('class_lecturers', schema=None) as batch_op:
        batch_op.alter_column('academic_year',
               existing_type=sa.VARCHAR(length=9),
               nullable=True)
        batch_op.alter_column('semester',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
