"""add_score_comment_updated_at_to_evaluation

Revision ID: 4c4d0efd9c13
Revises: b9271e9fad07
Create Date: 2025-05-14 02:13:33.748136

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4c4d0efd9c13'
down_revision = 'b9271e9fad07'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('class_lecturers', schema=None) as batch_op:
        batch_op.alter_column('semester',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('academic_year',
               existing_type=sa.VARCHAR(length=9),
               nullable=True)

    with op.batch_alter_table('classes', schema=None) as batch_op:
        batch_op.alter_column('semester',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('academic_year',
               existing_type=sa.VARCHAR(length=9),
               nullable=True)

    with op.batch_alter_table('evaluations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('score', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('comment', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('evaluations', schema=None) as batch_op:
        batch_op.drop_column('comment')
        batch_op.drop_column('score')
        batch_op.drop_column('updated_at')

    with op.batch_alter_table('classes', schema=None) as batch_op:
        batch_op.alter_column('academic_year',
               existing_type=sa.VARCHAR(length=9),
               nullable=True)
        batch_op.alter_column('semester',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('class_lecturers', schema=None) as batch_op:
        batch_op.alter_column('academic_year',
               existing_type=sa.VARCHAR(length=9),
               nullable=True)
        batch_op.alter_column('semester',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
