"""add lecturer_class_id

Revision ID: b9271e9fad07
Revises: 43256e4657c2
Create Date: 2025-05-13 17:19:45.948952

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b9271e9fad07'
down_revision = '43256e4657c2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('class_lecturers', schema=None) as batch_op:
        batch_op.alter_column('semester',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('academic_year',
               existing_type=sa.VARCHAR(length=9),
               nullable=True)

    with op.batch_alter_table('classes', schema=None) as batch_op:
        batch_op.alter_column('semester',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('academic_year',
               existing_type=sa.VARCHAR(length=9),
               nullable=True)

    with op.batch_alter_table('evaluations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('lecturer_class_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'class_lecturers', ['lecturer_class_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('evaluations', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('lecturer_class_id')

    with op.batch_alter_table('classes', schema=None) as batch_op:
        batch_op.alter_column('academic_year',
               existing_type=sa.VARCHAR(length=9),
               nullable=True)
        batch_op.alter_column('semester',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('class_lecturers', schema=None) as batch_op:
        batch_op.alter_column('academic_year',
               existing_type=sa.VARCHAR(length=9),
               nullable=True)
        batch_op.alter_column('semester',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
