"""add photo_url to lecturers

Revision ID: fe37588f5eba
Revises: 558d5ee4acc5
Create Date: 2025-05-11 04:07:40.729258

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fe37588f5eba'
down_revision = '558d5ee4acc5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lecturers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('photo_url', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lecturers', schema=None) as batch_op:
        batch_op.drop_column('photo_url')

    # ### end Alembic commands ###
